[tool.ruff]
lint.select = ["ALL"]
lint.ignore = ["D203", "D212", "TRY003", "PTH118", "RUF003", "A003", "INP001", "RUF015", "PERF401",
          "PTH123", "TC003", "D417", "RUF001", "TC001", "DTZ003", "G004", "B008", "PLR0913",
          "FIX004",
          # lint issues related to prompts. Ignored for now.
          D205, D207, D209, D213, D401, D400, D411, D413, D415, E501, W291, W293
          ]
lint.fixable = ["ALL"]
lint.unfixable = ["ERA001", "F841"]

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "tmp/",
    "__init__.py",
]

# Same as Black.
line-length = 119

# Assume Python 3.12.
target-version = "py312"

[tool.ruff.lint.per-file-ignores]
"test_*" = ["S101"]

[tool.ruff.lint.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[tool.black]
line-length = 119
target-version = ['py312']
preview = true

[tool.pyright]
pythonVersion = "3.12"
ignore = ["tmp/"]

[tool.pytest.ini_options]
pythonpath = [
  "."
]
addopts = "-p no:warnings"
